export interface ExportOptions {
  title: string
  content: string
  author?: string
  metadata?: Record<string, string>
}

export const pdfExportService = {
  async exportLessonToPDF(lesson: { title: string; subject: string; content: any; duration_minutes: number }): Promise<Blob> {
    const { jsPDF } = await import('jspdf')

    const pdf = new jsPDF()
    const pageWidth = pdf.internal.pageSize.getWidth()
    const pageHeight = pdf.internal.pageSize.getHeight()
    const margin = 10
    const contentWidth = pageWidth - 2 * margin

    let yPosition = margin

    // Title
    pdf.setFontSize(24)
    pdf.setFont('helvetica', 'bold')
    const titleLines = pdf.splitTextToSize(lesson.title, contentWidth)
    pdf.text(titleLines, margin, yPosition)
    yPosition += titleLines.length * 10 + 5

    // Metadata
    pdf.setFontSize(10)
    pdf.setFont('helvetica', 'normal')
    pdf.text(`Subject: ${lesson.subject}`, margin, yPosition)
    yPosition += 5
    pdf.text(`Duration: ${lesson.duration_minutes} minutes`, margin, yPosition)
    yPosition += 10

    // Content sections
    pdf.setFontSize(12)
    if (lesson.content?.sections && Array.isArray(lesson.content.sections)) {
      for (const section of lesson.content.sections) {
        // Section title
        pdf.setFont('helvetica', 'bold')
        pdf.text(section.title || 'Section', margin, yPosition)
        yPosition += 8

        // Section content
        pdf.setFont('helvetica', 'normal')
        pdf.setFontSize(10)
        const contentLines = pdf.splitTextToSize(section.content || '', contentWidth)
        pdf.text(contentLines, margin, yPosition)
        yPosition += contentLines.length * 6 + 5

        // Check if we need a new page
        if (yPosition > pageHeight - margin) {
          pdf.addPage()
          yPosition = margin
        }
      }
    }

    // Footer
    pdf.setFontSize(8)
    pdf.text(
      `Generated by School_AI_Custom on ${new Date().toLocaleDateString()}`,
      margin,
      pageHeight - margin
    )

    return pdf.output('blob')
  },

  async downloadLesson(lesson: { title: string; subject: string; content: any; duration_minutes: number }): Promise<void> {
    const blob = await this.exportLessonToPDF(lesson)
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `${lesson.title.replace(/\s+/g, '_')}.pdf`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  },
}
